# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  packer:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      run: "packer init ./src/infra/ami.pkr.hcl"

    - name: Run `packer validate`
      id: validate
      run: "packer validate ./src/infra/ami.pkr.hcl"

    - name: Zip file
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r /home/runner/work/webapp/webapp.zip /home/runner/work/webapp/webapp

    - name: Run `packer build`
      id: build
      run: "packer build ./src/infra/ami.pkr.hcl"